Add race script
FabulousCupcake/umamusume-wiki-scripts pull request #5
Opened 2021-03-30 21:01 UTC by robflop

This script extracts all relevant race info except:

- Assets
- Manual input fields (obv)
- Race Class (i.e. during which year(s) a race happens)
- Race fan gain

2021-03-30 22:08 UTC, robflop commented on cmd/race.js
> +  if (isNaN(length)) return;
I'll drop em.

2021-03-30 22:08 UTC, robflop commented on cmd/race.js
> +
Also dropping this then.

2021-03-30 22:13 UTC, FabulousCupcake commented on cmd/race.js
> +// Returns the season a race takes place during based on its month
```suggestion
// getRaceSeason converts month to season
```

2021-03-30 22:13 UTC, FabulousCupcake commented on cmd/race.js
> +// Returns the formal type of a race based on its length
```suggestion
// getRaceType converts track length from number to text

```

2021-03-30 22:13 UTC, FabulousCupcake commented on cmd/race.js
> +// Returns the season a race takes place during based on its month
Actually is this necessary to do in the script and as cargo table value? We send `month` anyways so a template should be able to resolve season name right?

2021-03-30 22:13 UTC, FabulousCupcake commented on cmd/race.js
> +// Returns the formal type of a race based on its length
This also could just be in the template; it's redundant to have track length and "race type" when its value is simply derived from track length

2021-03-30 22:16 UTC, robflop commented on cmd/race.js
> +// Returns the season a race takes place during based on its month
Good idea, we can definitely calculate it on the fly in the template.

2021-03-31 17:11 UTC, robflop commented
The script can now also extract fans gained! :tada:

2021-04-01 21:20 UTC, robflop commented on cmd/race.js
> +const RACE_CATEGORIES = {
We removed type and season because those could be extrapolated from distance and month in the template; We could also extrapolate race category from race group ands grade in the template. Should we?

2021-04-01 21:20 UTC, robflop commented on cmd/race.js
> +const RACE_TERRAIN = {
Same as above comment; this could be extrapolated in the template?

2021-04-01 21:20 UTC, robflop commented on cmd/race.js
> +const RACE_DIRECTION = {
Same as above comment; this could be extrapolated in the template?

2021-04-01 21:20 UTC, robflop commented on cmd/race.js
> +const RACE_COURSE = {
Same as above comment; this could be extrapolated in the template?

2021-04-02 19:29 UTC, FabulousCupcake requested changes

2021-04-02 19:29 UTC, FabulousCupcake commented on cmd/race.js
> +  const statement = db.prepare(RACE_QUERY + `WHERE race_instance.id=${id} LIMIT 1`);
```suggestion
  const statement = db.prepare(`${RACE_QUERY} WHERE race_instance.id=${id} LIMIT 1`);

```

2021-04-02 19:29 UTC, FabulousCupcake commented on cmd/race.js
> +  const statement = db.prepare(RACE_QUERY + RACE_BLACKLIST);
```suggestion
  const statement = db.prepare(`${RACE_QUERY} ${RACE_BLACKLIST}`);

```

2021-04-02 19:29 UTC, FabulousCupcake commented on cmd/race.js
> +LEFT OUTER JOIN single_mode_fan_count AS fan_sets ON program.fan_set_id = fan_sets.fan_set_id AND fan_sets."order" = 1 `;
```suggestion
LEFT OUTER JOIN single_mode_fan_count AS fan_sets ON program.fan_set_id = fan_sets.fan_set_id AND fan_sets."order" = 1`;

```

2021-04-02 19:29 UTC, FabulousCupcake commented on cmd/race.js
> +const RACE_QUERY = `SELECT race_instance."id" AS "id", race_instance."race_id" AS "race_id",
```suggestion
const RACE_QUERY = `
SELECT race_instance."id" AS "id", race_instance."race_id" AS "race_id",

```

2021-04-02 19:29 UTC, FabulousCupcake commented on cmd/race.js
> +const RACE_BLACKLIST = `WHERE race_instance.id < 580001 AND (
```suggestion
const RACE_BLACKLIST = `
WHERE race_instance.id < 580001 AND (
```

2021-04-02 19:30 UTC, FabulousCupcake commented on cmd/race.js
> +const RACE_CATEGORIES = {
Let's keep these for now

2021-04-02 19:31 UTC, FabulousCupcake commented on cmd/race.js
> +  params.track         = noop(RACE_TRACKS[data.race_track_id]); // Fetches EN name from ID or empty if EN name is not set
```suggestion
  params.track         = RACE_TRACKS[data.race_track_id] || ""; // Fetches EN name from ID or empty if EN name is not set

```

2021-04-02 19:32 UTC, robflop commented on cmd/race.js
> +const RACE_CATEGORIES = {
Okay 👍

2021-04-02 19:33 UTC, FabulousCupcake commented on cmd/race.js
> +  params.track         = noop(RACE_TRACKS[data.race_track_id]); // Fetches EN name from ID or empty if EN name is not set
Please use noop only for literally noop (i.e. we take already existing value from wiki); the goal is to make it easy to spot values that we do not provide from the script.

2021-04-02 19:35 UTC, robflop commented on cmd/race.js
> +  params.track         = noop(RACE_TRACKS[data.race_track_id]); // Fetches EN name from ID or empty if EN name is not set
Makes sense. Will change it to this.

2021-04-02 19:44 UTC, FabulousCupcake commented on cmd/race.js
> +const RACE_CATEGORIES = {
Marking as unresolved so we know which could/should be moved in the future

2021-04-02 19:45 UTC, merged